### ISSUE TITLE
integrate selenium grid to speed up cucumbers

### ISSUE THREAD

**Issue by polographer** [ideacrew/ea_enterprise#17]
there is a way to install selenium grid and run cucumbers on a separate container, that will remove the need to install chrome and do all the hacks to get the chromedriver, we just need to patch the cucumber-env.rb on the fly, this will remove the need to keep maintaining the cucumber integration and potentially we can paralelize the execution on the local machine, another great feature that testing edge or firefox its painless

MA has a similar feature for arm macs; https://github.com/health-connector/enroll/blob/master/.devcontainer/docker-compose.yml
```
  selenium-chrome:
    hostname: selenium-chrome
    image: seleniarm/standalone-chromium:latest
    shm_size: 2gb
    labels:
      - "autoheal=true"
    ports:
      - "4444:4444"
      - "7900:7900"
    healthcheck:
      test: '/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444'
      interval: 120s
      timeout: 60s
      retries: 30
      # start_period: 20s
```
